POST http://localhost:8890/events
content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAbWFpbC5jb20iLCJleHAiOjE3Mzk5NTY3MzUsInVzZXJJZCI6MX0.PRhYIieDnZkTSGYXpUtLbPqKyM9PEnkD2KRzNkTNgow

{
	"Name": "Event 1",
	"Description": "Description 1",
	"Location": "Location 1",
	"DateTime": "2025-02-17T11:27:00.000Z"
}